### PR TITLE
SkipExisting = false will overwrite the template

### PR DESCRIPTION
**Pull request by avnish30jn**
**Jira id**

C3-153

**Problem**

No way to overwrite the template if it already exists

**Solution**

Added support for overwriting the template vm. SkipExisting parameter when set to false would overwrite the template vm.

### CODE REVIEW

**Comment by sjpotter** [comment]
I think skipexisting should be turned into a flag of some sorts that determines what to do if it already exists

i.e. something like

Exists and can equal, skip, overwrite, error

**Comment by avnish30jn** [comment]
Yes, skipExisting comes into play only when the template exists.
if template exists{
      if skipExisting == true --> does nothing to the template and uses it
      else(skipExisting == false) --> overwrites the template (delete the template and upload a new one)
} else {
      uploads a new template irrespective of the value of skipExisting
}


Libretto errors out if template exists and skipExisting is set to false.

**Comment by sjpotter** [comment]
I understand, but what I'm saying is that there are 3 possible results that one wants if a template already exists

1) overwrite (what you add)
2) ignore (i.e. use what's there, how it currently works, if skip existing is set)
3) error out (how it currently works if skip existing isn't set)

your change doesn't capture all these 3 cases.  I might not want to overwrite while at the same time not wanting to boot what could be an unknown template.  

we need an enum that has 3 values and work based on that.

**Comment by pankajtandon12** [comment]
Waiting for above review comment to be incorporated.

**Pull request closed without merging**
