### PR TITLE
 Migrating from gvt to dep

### PR DESCRIPTION
**Pull request by avnish30jn**
Migrating from gvt to dep

**Output of dep status**

```
PROJECT                            CONSTRAINT     VERSION        REVISION  LATEST       PKGS USED
cloud.google.com/go                v0.21.0        v0.21.0        29f476f   v0.21.0      1
github.com/Azure/azure-sdk-for-go  ^2.2.0-beta    v2.2.0-beta    11d0965   v2.2.0-beta  14
github.com/Azure/go-autorest       v10.8.1        v10.8.1        eaa7994   v10.8.1      5
github.com/apcera/util             branch master  branch master  7a50bc8   7a50bc8      1
github.com/aws/aws-sdk-go          ^1.12.19       v1.13.41       94cafaa   v1.13.42     29
github.com/dgrijalva/jwt-go        v3.2.0         v3.2.0         06ea103   v3.2.0       1
github.com/go-ini/ini              v1.36.0        v1.36.0        6529cf7   v1.36.0      1
github.com/golang/protobuf         v1.1.0         v1.1.0         b4deda0   v1.1.0       1
github.com/jmespath/go-jmespath    *                             0b12d6b                1
github.com/mitchellh/mapstructure  branch master  branch master  00c29f5   00c29f5      1
github.com/pyr/egoscale            4897492                       4897492                1
github.com/rackspace/gophercloud   branch master  branch master  e00690e   e00690e      17
github.com/vmware/govmomi          ^0.12.0        v0.12.1        6103db2   v0.12.1      15
golang.org/x/crypto                branch master  branch master  1f94bef   4ec37c6      8
golang.org/x/net                   branch master  branch master  640f462   640f462      2
golang.org/x/oauth2                branch master  branch master  cdc340f   cdc340f      5
google.golang.org/api              branch master  branch master  db8ef49   20530fd      5
google.golang.org/appengine        v1.0.0         v1.0.0         150dc57   v1.0.0       10
```

### CODE REVIEW

**Comment by pankajtandon12** [comment]
Please use a feature-branch than 'master' unless the e2e c3 functionalities get tested.

**Comment by avnish30jn** [comment]
Changed base branch to feature-dep-migration.

**Review by pankajtandon12 — APPROVED** [review]
LGTM

**Comment by virup** [comment]
Thanks for doing this. I am guessing you ran the c3 code and verified that everything downstream compiles and works as expected.

**Comment by virup** [comment]
Also, why are you not checking this into the integration branch but creating a new one?

**Review by virup — APPROVED** [review]
Had a couple of comments.

**Comment by avnish30jn** [comment]
Yes tested several operations after moving these changes in c3 repo and creating container from it.

- add cloud provider (vmware)
- edit cloud provider (vmware)
- create visor
- create vmware cluster
- deployed app on the c3 clusters
- performed operations on app
- created 3-node cluster with static ip
- created and deployed infra vms and performed operations on the apps

The PR is raised on the feature branch to avoid any surprises in c3ntry on integration builds. Once the migration from older c3ntry to new c3 is being done i'll raise PR to the main branch from the feature branch.

**Pull request merged**
