### PR TITLE
Function to return the network list in all datacenters added

### PR DESCRIPTION
**Pull request by avnish30jn**
**Jira ID**

C3-60

**Problem**

No functionality to get the Networks in vsphere cloud

**Solution**

Added support for returning the Networks list

**Testing**

Unit testing done - Returns the networks in datacenter in the vcenter server

**O/p**
{"Apporbit-Lab":["VMprivate-network","VM Limited Bandwidth","VM Network","VM-private-net2","VM-net-Priv","Private Network","VM-Private","VMs Limited Bandwidth","vm-priv-net","visor_network","VM-priv-net","VM Private"]}

### CODE REVIEW

**Comment by sjpotter** [comment]
So, you've been writing a lot of what I'd classify as "helper" functions.  I'm wondering if they are best done as taking a vm struct, or if they'd be better separate from it.  i.e. they really have nothing to do with a vm, its just that libretto was based around that.

would it be useful to separate out the loging in code into its own struct that can be embedded in the vm struct?

**Comment by avnish30jn** [comment]
The basic functions to perform the tasks in libretto are using vm struct. For eg: setUpSession, findDataceter etc. vm struct has username, password, host of vcenter server which are used for setting up connection. vm struct has finder, collector, context which is being used by almost all libretto helper functions.

This could have been separated but this will introduce too much of duplicate code.

**Comment by avnish30jn** [comment]
There are many helper functions in libretto that uses vm struct to perform that task. Changing the vm struct means changing so many helper functions. 
For eg : the vcenter host, login credentials comes with vm struct, context comes with vm struct, finder, collector and client is in vm struct which are used in every helper function in libretto. 
This will happen for other clouds as well. Too much complexity.

**Review by pankajtandon12 — APPROVED** [review]
LGTM

**Pull request merged**
